import assert from 'node:assert/strict';
import { test } from 'node:test';
import { buildPeople } from '../src/build/people.ts';

/**
 * Sort names order the People and Years screens, so a malformed one moves a
 * person somewhere nobody would look for them. The convention is "Last, First"
 * with titles dropped: "Voinovich, George", "Moss, Otis, Jr.".
 *
 * Four once broke it — life dates and alternate names in parentheses read as
 * surnames ("2002), Helen Karpinski (1899 –"), a doubled comma, and a kept
 * honorific — because they were generated by taking the last word.
 */

const titles = /\b(Dr|Rev|Reverend|Hon|Honorable|Mayor|Senator|Bishop|Judge|Sister|Father|Ambassador|Rabbi|Imam|Msgr|Monsignor|Professor|Prof)\b\.?/;

test('every sort name reads "Last, First", with no dates, brackets or titles', () => {
  const problems = buildPeople()
    .filter((person) => !/^[^,\d()]+, [^\d()]+$/.test(person.sortName) || /,,/.test(person.sortName) || titles.test(person.sortName))
    .map((person) => `${person.name} => "${person.sortName}"`);
  assert.deepEqual(problems, []);
});
