import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { sourcePath } from './data-utils.js';

export const curatedEntityModelPath = resolve('data/cihof_curated_entities.json');

export const entityTypes = ['Person', 'Community', 'Place', 'Organization', 'Event', 'Theme', 'Media'];
export const relationshipTypes = [
  'has_theme',
  'member_of_community',
  'associated_with_place',
  'associated_with_organization',
  'participated_in_event',
  'inducted_by_candidate',
  'inducted_in_class',
  'has_media',
  'legacy_related_candidate',
  'related_to',
];
export const provenanceValues = ['documented', 'curated', 'inferred'];

export function loadCuratedEntityModel(options = {}) {
  const optional = options.optional !== false;
  if (!existsSync(curatedEntityModelPath)) {
    if (optional) return emptyCuratedEntityModel();
    throw new Error(`Missing curated entity model file: ${curatedEntityModelPath}`);
  }

  try {
    const model = JSON.parse(readFileSync(curatedEntityModelPath, 'utf8'));
    return model && typeof model === 'object' ? normalizeCuratedEntityModel(model) : emptyCuratedEntityModel();
  } catch (error) {
    throw new Error(`Could not read curated entity model: ${error.message}`);
  }
}

export function buildEntityModel(inductees, curatedModel = loadCuratedEntityModel()) {
  const entities = [];
  const relationships = [];
  const addedEntityIds = new Set();
  const addedRelationshipIds = new Set();
  const peopleByName = buildPeopleByName(inductees);

  const addEntity = (entity) => {
    entities.push(entity);
    addedEntityIds.add(entity.id);
  };

  const addRelationship = (relationship) => {
    if (addedRelationshipIds.has(relationship.id)) return;
    relationships.push(relationship);
    addedRelationshipIds.add(relationship.id);
  };

  inductees.forEach((inductee) => {
    addEntity(personEntity(inductee));
  });

  inductees.forEach((inductee) => {
    const personId = personEntityId(inductee.id);

    addClassYearEntityAndRelationship(inductee, addEntity, addRelationship, addedEntityIds);
    addThemeEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds);
    addNationalityHeritageEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds);
    addCommunityEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds);
    addMediaEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds);
    addInductedByRelationship(inductee, peopleByName, addEntity, addRelationship, addedEntityIds);

    inductee.relatedIds.forEach((relatedId) => {
      addRelationship(entityRelationship({
        sourceEntityId: personId,
        targetEntityId: personEntityId(relatedId),
        type: 'legacy_related_candidate',
        displayLabel: 'Suggested related profile',
        shortDescription: 'Legacy generated relatedIds suggestion retained for migration compatibility.',
        confidence: 'inferred',
        sourceField: 'relatedIds',
        sourceRecordId: inductee.id,
        note: 'Generated by the legacy inductee adapter; needs curatorial review before being treated as fact.',
      }));
    });
  });

  const curatedEntities = Array.isArray(curatedModel.entities) ? curatedModel.entities : [];
  const curatedRelationships = Array.isArray(curatedModel.relationships) ? curatedModel.relationships : [];

  curatedEntities.forEach((entity) => addEntity(entity));
  curatedRelationships.forEach((relationship) => addRelationship(relationship));

  const entityDocument = {
    schemaVersion: 1,
    source: {
      generator: 'scripts/entity-model.js',
      adapter: 'legacy-inductee-v1',
      legacySource: relativePath(sourcePath),
      curatedSource: relativePath(curatedEntityModelPath),
      notes: 'Generated as a parallel entity model; public/data/inductees.json remains the legacy runtime feed.',
    },
    entityTypes,
    entities: entities.sort((a, b) => entitySortKey(a).localeCompare(entitySortKey(b))),
  };

  const relationshipDocument = {
    schemaVersion: 1,
    source: {
      generator: 'scripts/entity-model.js',
      adapter: 'legacy-inductee-v1',
      legacySource: relativePath(sourcePath),
      curatedSource: relativePath(curatedEntityModelPath),
      notes: 'Relationships are stored separately from entities for incremental graph migration.',
    },
    relationshipTypes,
    relationships: relationships.sort((a, b) => a.id.localeCompare(b.id)),
  };

  const validation = validateEntityModel(entityDocument, relationshipDocument);

  return {
    entityDocument,
    relationshipDocument,
    report: buildEntityModelReport(entityDocument, relationshipDocument, curatedModel, validation),
    validation,
  };
}

export function validateEntityModel(entityDocument, relationshipDocument) {
  const errors = [];
  const warnings = [];
  const entities = entityDocument?.entities;
  const relationships = relationshipDocument?.relationships;

  if (!entityDocument || typeof entityDocument !== 'object') errors.push('Entity document must be an object.');
  if (!relationshipDocument || typeof relationshipDocument !== 'object') errors.push('Relationship document must be an object.');
  if (!Array.isArray(entities)) errors.push('Entity document must contain an entities array.');
  if (!Array.isArray(relationships)) errors.push('Relationship document must contain a relationships array.');
  if (errors.length > 0) return { errors, warnings };

  const entityIdCounts = countValues(entities.map((entity) => entity?.id));
  const relationshipIdCounts = countValues(relationships.map((relationship) => relationship?.id));
  const entityIds = new Set(entities.map((entity) => entity?.id).filter(Boolean));

  duplicateValues(entityIdCounts).forEach((id) => errors.push(`Duplicate entity id: ${id}`));
  duplicateValues(relationshipIdCounts).forEach((id) => errors.push(`Duplicate relationship id: ${id}`));

  entities.forEach((entity, index) => validateEntity(entity, index, entityIds, errors, warnings));
  relationships.forEach((relationship, index) => validateRelationship(relationship, index, entityIds, errors, warnings));

  return { errors, warnings };
}

function validateEntity(entity, index, entityIds, errors, warnings) {
  const label = entity?.id || `entities[${index}]`;
  if (!entity || typeof entity !== 'object' || Array.isArray(entity)) {
    errors.push(`${label}: entity must be an object.`);
    return;
  }

  requireString(entity.id, `${label}: id`, errors);
  requireString(entity.displayName, `${label}: displayName`, errors);
  requireString(entity.type, `${label}: type`, errors);
  requireString(entity.shortDescription, `${label}: shortDescription`, errors);
  if (!entityTypes.includes(entity.type)) errors.push(`${label}: invalid entity type "${entity.type}".`);
  validateProvenance(entity.provenance, `${label}: provenance`, errors);

  if (entity.media !== undefined) {
    if (!Array.isArray(entity.media)) {
      errors.push(`${label}: media must be an array when present.`);
    } else {
      entity.media.forEach((mediaItem, mediaIndex) => {
        const mediaLabel = `${label}: media[${mediaIndex}]`;
        if (!mediaItem || typeof mediaItem !== 'object' || Array.isArray(mediaItem)) {
          errors.push(`${mediaLabel} must be an object.`);
          return;
        }
        requireString(mediaItem.kind, `${mediaLabel}: kind`, errors);
        if (mediaItem.entityId && !entityIds.has(mediaItem.entityId)) {
          errors.push(`${mediaLabel}: orphaned media entity reference "${mediaItem.entityId}".`);
        }
      });
    }
  }

  if (entity.dateRange !== undefined && (!entity.dateRange || typeof entity.dateRange !== 'object' || Array.isArray(entity.dateRange))) {
    errors.push(`${label}: dateRange must be an object when present.`);
  }

  if (entity.location !== undefined) {
    if (!entity.location || typeof entity.location !== 'object' || Array.isArray(entity.location)) errors.push(`${label}: location must be an object when present.`);
    else requireString(entity.location.displayName, `${label}: location.displayName`, errors);
  }

  if (entity.id && !entity.id.includes(':')) warnings.push(`${label}: id should include a type namespace such as person: or theme:.`);
}

function validateRelationship(relationship, index, entityIds, errors) {
  const label = relationship?.id || `relationships[${index}]`;
  if (!relationship || typeof relationship !== 'object' || Array.isArray(relationship)) {
    errors.push(`${label}: relationship must be an object.`);
    return;
  }

  requireString(relationship.id, `${label}: id`, errors);
  requireString(relationship.sourceEntityId, `${label}: sourceEntityId`, errors);
  requireString(relationship.targetEntityId, `${label}: targetEntityId`, errors);
  requireString(relationship.type, `${label}: type`, errors);
  requireString(relationship.displayLabel, `${label}: displayLabel`, errors);
  if (!relationshipTypes.includes(relationship.type)) errors.push(`${label}: invalid relationship type "${relationship.type}".`);
  if (relationship.sourceEntityId && !entityIds.has(relationship.sourceEntityId)) errors.push(`${label}: orphaned sourceEntityId "${relationship.sourceEntityId}".`);
  if (relationship.targetEntityId && !entityIds.has(relationship.targetEntityId)) errors.push(`${label}: orphaned targetEntityId "${relationship.targetEntityId}".`);
  validateProvenance(relationship.provenance, `${label}: provenance`, errors);
}

function validateProvenance(provenance, label, errors) {
  if (!provenance || typeof provenance !== 'object' || Array.isArray(provenance)) {
    errors.push(`${label} must be an object.`);
    return;
  }
  requireString(provenance.source, `${label}.source`, errors);
  requireString(provenance.confidence, `${label}.confidence`, errors);
  if (!provenanceValues.includes(provenance.confidence)) errors.push(`${label}.confidence has invalid value "${provenance.confidence}".`);
}

function addClassYearEntityAndRelationship(inductee, addEntity, addRelationship, addedEntityIds) {
  if (!inductee.classYear) return;

  const id = classEventEntityId(inductee.classYear);
  if (!addedEntityIds.has(id)) {
    addEntity({
      id,
      displayName: `Class of ${inductee.classYear}`,
      type: 'Event',
      shortDescription: `Cleveland International Hall of Fame class year ${inductee.classYear}.`,
      dateRange: { start: String(inductee.classYear), end: String(inductee.classYear), label: `Class of ${inductee.classYear}` },
      provenance: provenance({
        confidence: 'curated',
        sourceField: 'classYear',
        note: 'Generated class event from current inductee class-year data.',
      }),
      attributes: { classYear: inductee.classYear, generatedFromLegacyClassYear: true },
    });
  }

  addRelationship(entityRelationship({
    sourceEntityId: personEntityId(inductee.id),
    targetEntityId: id,
    type: 'inducted_in_class',
    displayLabel: `Class of ${inductee.classYear}`,
    shortDescription: `${inductee.name} is in the ${inductee.classYear} class.`,
    confidence: 'curated',
    sourceField: 'classYear',
    sourceRecordId: inductee.id,
  }));
}

function addThemeEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds) {
  inductee.themeTags.forEach((theme) => {
    const id = themeEntityId(theme);
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: theme,
        type: 'Theme',
        shortDescription: `Story theme used to group inductees connected to ${theme.toLowerCase()}.`,
        provenance: provenance({
          confidence: inductee.themeTagsSource === 'curated' ? 'curated' : 'inferred',
          sourceField: 'themeTags',
          note: 'Generated from current inductee theme tags.',
        }),
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'has_theme',
      displayLabel: `Theme: ${theme}`,
      shortDescription: `${inductee.name} is associated with the ${theme} theme.`,
      confidence: inductee.themeTagsSource === 'curated' ? 'curated' : 'inferred',
      sourceField: 'themeTags',
      sourceRecordId: inductee.id,
      note: inductee.themeTagsSource === 'curated' ? 'Approved theme metadata.' : 'Generated theme metadata; needs curatorial review.',
    }));
  });
}

function addCommunityEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds) {
  inductee.communityTags.forEach((community) => {
    const id = communityEntityId(community);
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: community,
        type: 'Community',
        shortDescription: `Community label used in the current curated metadata.`,
        provenance: provenance({
          confidence: 'curated',
          sourceField: 'communityTags',
          note: 'Generated from approved community metadata where available.',
        }),
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'member_of_community',
      displayLabel: `Community: ${community}`,
      shortDescription: `${inductee.name} is associated with ${community}.`,
      confidence: 'curated',
      sourceField: 'communityTags',
      sourceRecordId: inductee.id,
    }));
  });
}

function addNationalityHeritageEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds) {
  inductee.countryTags.forEach((country) => {
    const id = communityEntityId(country);
    const confidence = inductee.countryTagsSource === 'curated' ? 'curated' : 'inferred';
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: country,
        type: 'Community',
        shortDescription: 'Nationality or heritage label used for more specific browsing than broad region metadata.',
        provenance: provenance({
          confidence,
          sourceField: 'countryTags',
          note: confidence === 'curated'
            ? 'Generated from curator-approved nationality or heritage metadata.'
            : 'Generated from nationality and heritage references in source text; needs curatorial review.',
        }),
        attributes: {
          communityKind: 'nationality-or-heritage',
          legacyRegion: inductee.region,
        },
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'member_of_community',
      displayLabel: `Nationality / Heritage: ${country}`,
      shortDescription: `${inductee.name} is associated with ${country}.`,
      confidence,
      sourceField: 'countryTags',
      sourceRecordId: inductee.id,
      note: confidence === 'curated' ? 'Approved nationality or heritage metadata.' : 'Generated nationality or heritage metadata; needs curatorial review.',
    }));
  });
}

function addMediaEntitiesAndRelationships(inductee, addEntity, addRelationship, addedEntityIds) {
  const primaryImageUrl = inductee.primaryImageUrl;
  if (primaryImageUrl) {
    const id = `media:primary-image:${inductee.id}`;
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: `${inductee.name} primary portrait`,
        type: 'Media',
        shortDescription: `Primary image currently associated with ${inductee.name}.`,
        media: [{ kind: 'image', role: 'source', url: primaryImageUrl, altText: inductee.imageAltText }],
        provenance: provenance({
          confidence: mediaConfidence(inductee.imageRightsStatus),
          sourceField: 'primaryImageUrl',
          sourceRecordId: inductee.id,
          note: 'Generated from the current media manifest or source image URL.',
        }),
        attributes: {
          mediaType: 'image',
          url: primaryImageUrl,
          rightsStatus: inductee.imageRightsStatus,
          approvedForKiosk: inductee.imageRightsStatus === 'approved',
        },
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'has_media',
      displayLabel: 'Primary portrait',
      shortDescription: `${inductee.name} has a primary portrait image.`,
      confidence: mediaConfidence(inductee.imageRightsStatus),
      sourceField: 'primaryImageUrl',
      sourceRecordId: inductee.id,
    }));
  }

  inductee.youtubeVideoIds.forEach((youtubeVideoId) => {
    const id = `media:youtube:${youtubeVideoId}`;
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: `${inductee.name} video`,
        type: 'Media',
        shortDescription: `Video currently associated with ${inductee.name}.`,
        media: [{ kind: 'video', role: 'source', url: `https://www.youtube.com/watch?v=${youtubeVideoId}` }],
        provenance: provenance({
          confidence: mediaConfidence(inductee.videoRightsStatus),
          sourceField: 'youtubeVideoIds',
          sourceRecordId: inductee.id,
          note: 'Generated from current video metadata.',
        }),
        attributes: {
          mediaType: 'video',
          youtubeVideoId,
          rightsStatus: inductee.videoRightsStatus,
          approvedForKiosk: inductee.videoRightsStatus === 'approved',
        },
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'has_media',
      displayLabel: 'Video',
      shortDescription: `${inductee.name} has linked video media.`,
      confidence: mediaConfidence(inductee.videoRightsStatus),
      sourceField: 'youtubeVideoIds',
      sourceRecordId: inductee.id,
    }));
  });

  inductee.localVideoPaths.forEach((localVideoPath) => {
    const id = `media:local-video:${slugify(localVideoPath)}`;
    if (!addedEntityIds.has(id)) {
      addEntity({
        id,
        displayName: `${inductee.name} local video`,
        type: 'Media',
        shortDescription: `Localized video currently associated with ${inductee.name}.`,
        media: [{ kind: 'video', role: 'runtime', url: `/${localVideoPath.replace(/^\/+/, '')}` }],
        provenance: provenance({
          confidence: mediaConfidence(inductee.videoRightsStatus),
          sourceField: 'localVideoPaths',
          sourceRecordId: inductee.id,
          note: 'Generated from current localized video metadata.',
        }),
        attributes: {
          mediaType: 'video',
          runtimePath: `/${localVideoPath.replace(/^\/+/, '')}`,
          rightsStatus: inductee.videoRightsStatus,
          approvedForKiosk: inductee.videoRightsStatus === 'approved',
        },
      });
    }

    addRelationship(entityRelationship({
      sourceEntityId: personEntityId(inductee.id),
      targetEntityId: id,
      type: 'has_media',
      displayLabel: 'Localized video',
      shortDescription: `${inductee.name} has localized video media.`,
      confidence: mediaConfidence(inductee.videoRightsStatus),
      sourceField: 'localVideoPaths',
      sourceRecordId: inductee.id,
    }));
  });
}

function addInductedByRelationship(inductee, peopleByName, addEntity, addRelationship, addedEntityIds) {
  if (!inductee.inductedBy) return;

  const matchedPerson = findPersonByName(inductee.inductedBy, peopleByName);
  const targetId = matchedPerson ? personEntityId(matchedPerson.id) : `person-candidate:${slugify(inductee.inductedBy)}`;

  if (!matchedPerson && !addedEntityIds.has(targetId)) {
    addEntity({
      id: targetId,
      displayName: inductee.inductedBy,
      type: 'Person',
      shortDescription: 'Named in an inducted-by field; candidate person entity pending curatorial review.',
      provenance: provenance({
        confidence: 'inferred',
        sourceField: 'inductedBy',
        note: 'Generated as a candidate endpoint so relationship references are not orphaned.',
      }),
      attributes: { candidateEntity: true, candidateReason: 'inductedBy reference' },
    });
  }

  addRelationship(entityRelationship({
    sourceEntityId: personEntityId(inductee.id),
    targetEntityId: targetId,
    type: 'inducted_by_candidate',
    displayLabel: `Inducted by ${inductee.inductedBy}`,
    shortDescription: `${inductee.name} has an inducted-by reference to ${inductee.inductedBy}.`,
    confidence: matchedPerson ? 'curated' : 'inferred',
    sourceField: 'inductedBy',
    sourceRecordId: inductee.id,
    note: matchedPerson
      ? 'Matched an existing person entity by name; still treated as a candidate relationship.'
      : 'Target person was generated as a candidate entity; needs curatorial review.',
  }));
}

function personEntity(inductee) {
  const media = [];
  if (inductee.primaryImageUrl) {
    media.push({
      entityId: `media:primary-image:${inductee.id}`,
      kind: 'image',
      role: 'primary',
      url: inductee.primaryImageUrl,
      altText: inductee.imageAltText,
    });
  }

  inductee.youtubeVideoIds.forEach((youtubeVideoId) => {
    media.push({
      entityId: `media:youtube:${youtubeVideoId}`,
      kind: 'video',
      role: 'source',
      url: `https://www.youtube.com/watch?v=${youtubeVideoId}`,
    });
  });

  inductee.localVideoPaths.forEach((localVideoPath) => {
    media.push({
      entityId: `media:local-video:${slugify(localVideoPath)}`,
      kind: 'video',
      role: 'runtime',
      url: `/${localVideoPath.replace(/^\/+/, '')}`,
    });
  });

  return compactObject({
    id: personEntityId(inductee.id),
    displayName: inductee.name,
    type: 'Person',
    shortDescription: inductee.storySummary || summarize(inductee.bioText, 220) || `${inductee.name}, Cleveland International Hall of Fame inductee.`,
    media,
    dateRange: inductee.classYear
      ? { start: String(inductee.classYear), end: String(inductee.classYear), label: `Class of ${inductee.classYear}` }
      : undefined,
    location: inductee.region ? { displayName: inductee.region, region: inductee.region } : undefined,
    provenance: provenance({
      confidence: inductee.approvalStatus === 'approved' ? 'documented' : 'curated',
      sourceRecordId: inductee.id,
      note: 'Adapted from the current inductee record.',
    }),
    attributes: {
      legacyInducteeId: inductee.id,
      classYear: inductee.classYear,
      decade: inductee.decade,
      region: inductee.region,
      countryTags: inductee.countryTags,
      countryTagsSource: inductee.countryTagsSource,
      profileUrl: inductee.profileUrl,
      inductedBy: inductee.inductedBy,
      approvalStatus: inductee.approvalStatus,
      reviewPriority: inductee.reviewPriority,
      featured: inductee.featured,
      featuredCandidate: inductee.featuredCandidate,
      hasVideo: inductee.hasVideo,
      hasGallery: inductee.hasGallery,
      themeTags: inductee.themeTags,
      communityTags: inductee.communityTags,
      relatedIds: inductee.relatedIds,
      physicalWall: {
        physicalRow: inductee.physicalRow,
        physicalColumn: inductee.physicalColumn,
        physicalPanel: inductee.physicalPanel,
        wallLabel: inductee.wallLabel,
        wallCoordinates: inductee.wallCoordinates,
        physicalPortraitPresent: inductee.physicalPortraitPresent,
      },
    },
  });
}

function entityRelationship({
  sourceEntityId,
  targetEntityId,
  type,
  displayLabel,
  shortDescription,
  confidence,
  sourceField,
  sourceRecordId,
  note,
}) {
  return compactObject({
    id: relationshipId(sourceEntityId, type, targetEntityId),
    sourceEntityId,
    targetEntityId,
    type,
    displayLabel,
    shortDescription,
    provenance: provenance({ confidence, sourceField, sourceRecordId, note }),
  });
}

function buildEntityModelReport(entityDocument, relationshipDocument, curatedModel, validation) {
  return {
    schemaVersion: 1,
    source: {
      generator: 'scripts/entity-model.js',
      entities: 'public/data/entities.json',
      relationships: 'public/data/entity-relationships.json',
      curatedSource: relativePath(curatedEntityModelPath),
    },
    totals: {
      entities: entityDocument.entities.length,
      relationships: relationshipDocument.relationships.length,
      curatedEntities: Array.isArray(curatedModel.entities) ? curatedModel.entities.length : 0,
      curatedRelationships: Array.isArray(curatedModel.relationships) ? curatedModel.relationships.length : 0,
    },
    entityTypes: countBy(entityDocument.entities.map((entity) => entity.type), 'type'),
    relationshipTypes: countBy(relationshipDocument.relationships.map((relationship) => relationship.type), 'type'),
    provenance: countBy([
      ...entityDocument.entities.map((entity) => entity.provenance?.confidence),
      ...relationshipDocument.relationships.map((relationship) => relationship.provenance?.confidence),
    ].filter(Boolean), 'confidence'),
    phaseCoverage: {
      phase1: {
        personEntities: entityDocument.entities.filter((entity) => entity.type === 'Person' && entity.id.startsWith('person:')).length,
        candidatePersonEntities: entityDocument.entities.filter((entity) => entity.type === 'Person' && entity.id.startsWith('person-candidate:')).length,
        themeEntities: entityDocument.entities.filter((entity) => entity.type === 'Theme').length,
        classEvents: entityDocument.entities.filter((entity) => entity.type === 'Event' && entity.id.startsWith('event:class-of-')).length,
        inductedByCandidates: relationshipDocument.relationships.filter((relationship) => relationship.type === 'inducted_by_candidate').length,
      },
      phase2: {
        curatedEntitiesReady: true,
        supportedTypes: ['Community', 'Organization', 'Place', 'Event'],
      },
    },
    validation,
  };
}

function emptyCuratedEntityModel() {
  return {
    schemaVersion: 1,
    source: {},
    reviewGuidance: {},
    entities: [],
    relationships: [],
  };
}

function normalizeCuratedEntityModel(model) {
  return {
    ...emptyCuratedEntityModel(),
    ...model,
    entities: Array.isArray(model.entities) ? model.entities : [],
    relationships: Array.isArray(model.relationships) ? model.relationships : [],
  };
}

function buildPeopleByName(inductees) {
  const map = new Map();
  inductees.forEach((inductee) => {
    const names = new Set([normalizeName(inductee.name), normalizeName(stripHonorifics(inductee.name))]);
    names.forEach((name) => {
      if (name && !map.has(name)) map.set(name, inductee);
    });
  });
  return map;
}

function findPersonByName(name, peopleByName) {
  const normalized = normalizeName(name);
  const stripped = normalizeName(stripHonorifics(name));
  if (peopleByName.has(normalized)) return peopleByName.get(normalized);
  if (peopleByName.has(stripped)) return peopleByName.get(stripped);

  const tokens = stripped.split(' ').filter((token) => token.length > 1);
  if (tokens.length < 2) return null;

  for (const [candidateName, inductee] of peopleByName.entries()) {
    const candidateTokens = new Set(candidateName.split(' '));
    if (tokens.every((token) => candidateTokens.has(token))) return inductee;
  }

  return null;
}

function mediaConfidence(status) {
  return status === 'approved' ? 'documented' : 'curated';
}

function provenance({ confidence, sourceField, sourceRecordId, note }) {
  return compactObject({
    source: 'legacy-inductee-adapter',
    sourcePath: relativePath(sourcePath),
    confidence,
    sourceRecordId,
    sourceField,
    note,
  });
}

function personEntityId(inducteeId) {
  return `person:${inducteeId}`;
}

function themeEntityId(theme) {
  return `theme:${slugify(theme)}`;
}

function communityEntityId(community) {
  return `community:${slugify(community)}`;
}

function classEventEntityId(year) {
  return `event:class-of-${year}`;
}

function relationshipId(sourceEntityId, type, targetEntityId) {
  return `rel:${slugify(sourceEntityId)}:${type}:${slugify(targetEntityId)}`;
}

function entitySortKey(entity) {
  return `${entity.type}:${entity.displayName}:${entity.id}`;
}

function compactObject(record) {
  return Object.fromEntries(Object.entries(record).filter(([, value]) => {
    if (value === undefined || value === null || value === '') return false;
    if (Array.isArray(value) && value.length === 0) return false;
    return true;
  }));
}

function requireString(value, label, errors) {
  if (typeof value !== 'string' || value.trim().length === 0) errors.push(`${label} must be a non-empty string.`);
}

function countValues(values) {
  return values.reduce((map, value) => {
    if (!value) return map;
    return map.set(value, (map.get(value) ?? 0) + 1);
  }, new Map());
}

function duplicateValues(counts) {
  return Array.from(counts.entries()).filter(([, count]) => count > 1).map(([value]) => value);
}

function countBy(values, keyName) {
  const counts = values.reduce((map, value) => map.set(value, (map.get(value) ?? 0) + 1), new Map());
  return Array.from(counts.entries())
    .map(([value, count]) => ({ [keyName]: value, count }))
    .sort((a, b) => b.count - a.count || String(a[keyName]).localeCompare(String(b[keyName])));
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function normalizeName(name) {
  return stripHonorifics(name)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function stripHonorifics(name) {
  return String(name)
    .replace(/^(ambassador|bishop|dr\.?|father|former mayor|fr\.?|hon\.?|honorable|mayor|reverend|rev\.?|senator|sister)\s+/i, '')
    .replace(/\b(jr\.?|sr\.?|ii|iii|iv|ph\.?d\.?|m\.?d\.?)$/i, '')
    .trim();
}

function summarize(text, limit) {
  if (!text || text.length <= limit) return text;
  const slice = text.slice(0, limit + 1);
  const wordEnd = slice.lastIndexOf(' ');
  return `${slice.slice(0, wordEnd > 80 ? wordEnd : limit).trim()}...`;
}

function relativePath(path) {
  return path.replace(`${process.cwd()}/`, '');
}
